version: "3.9"

services:
  postgres:
    image: postgis/postgis:latest
    container_name: go_starter-dev-db
    ports:
      - "5432:5432"
    volumes:
      - go_starter-dev_postgres_data:/var/lib/postgresql/data
    networks:
      - gateway
    environment:
      POSTGRES_DB: go_starter
      POSTGRES_USER: monzim
      POSTGRES_PASSWORD: 123456789

networks:
  gateway:
    external: true

volumes:
  go_starter-dev_postgres_data:
