name: devsprint
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  go_router: ^14.0.1
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  font_awesome_flutter: ^10.7.0
  logger: ^2.2.0
  flutter_localizations:
    sdk: flutter
  # intl: ^0.19.0

  #Azizur
  permission_handler: ^11.3.1
  # mapbox_maps_flutter: ^1.1.0
  geolocator: ^11.0.0
  fluttertoast: ^8.2.5
  flutter_screenutil: ^5.9.0
  # easy_search_bar: ^2.0.3
  # flutter_search_bar: ^3.0.0
  material_floating_search_bar_2: ^0.5.0


  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  generate: true
  uses-material-design: true
